export const doctorData = [
  {
    id: 1,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 2,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 3,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 4,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 5,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 6,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 7,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 8,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 9,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 10,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 11,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 12,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 13,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 14,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 15,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 16,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 17,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 18,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 19,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 20,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 21,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 22,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 23,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 24,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 25,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 26,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 27,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 28,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 29,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 30,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 31,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 32,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 33,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 34,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 35,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 36,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 37,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 38,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 39,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 40,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 41,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 42,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 43,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 44,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 45,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 46,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 47,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 48,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 49,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 50,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 51,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 52,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 53,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 54,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 55,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 56,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 57,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 58,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 59,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 60,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 61,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 62,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 63,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 64,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 65,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 66,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 67,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 68,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 69,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 70,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 71,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 72,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 73,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 74,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 75,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 76,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 77,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 78,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 79,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 80,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 81,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 81,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 83,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 84,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 85,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 86,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 87,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 88,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 89,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 90,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 91,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 92,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 93,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 94,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 95,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 96,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
  {
    id: 97,
    name: "iftekhar Ahmed",
    img: "assets/img/doctor-thumb-06.jpg",
    designation: "Gynecologist",
    location: "United States, San Francisco",
  },
  {
    id: 98,
    name: "Ayman Shaikh",
    img: "assets/img/doctor-thumb-05.jpg",
    designation: "Radiologist",
    location: "United States, San Francisco",
  },
  {
    id: 99,
    name: "Wasim Gujrati",
    img: "assets/img/doctor-thumb-04.jpg",
    designation: "Physical Therapist",
    location: "United States, San Francisco",
  },
  {
    id: 100,
    name: "Ammar",
    img: "assets/img/doctor-thumb-03.jpg",
    designation: "General Surgery",
    location: "United States, San Francisco",
  },
];


export const clinicData = [
  {
    id: 1,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 2,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 3,
    name: 'Shifa Clinic',
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 4,
    name: 'Sadaf Clinic',
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 5,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 6,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 7,
    name: 'Shifa Clinic',
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 8,
    name: 'Sadaf Clinic',
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 9,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 10,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 11,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 12,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 13,
    name: 'Shifa Clinic',
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 14,
    name: 'Sadaf Clinic',
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 15,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 16,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 17,
    name: 'Shifa Clinic',
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 18,
    name: 'Sadaf Clinic',
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 19,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 20,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 21,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 22,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 23,
    name: 'Shifa Clinic',
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 24,
    name: 'Sadaf Clinic',
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 25,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 26,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 27,
    name: 'Shifa Clinic',
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 28,
    name: 'Sadaf Clinic',
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 29,
    name: 'Poly Clinic',
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 30,
    name: 'Mega Clinic',
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
];

export const patientData = [
  {
    id: 1,
    name: 'Amalia',
    age: 23,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 2,
    name: 'Shizaa Fatema',
    age: 23,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 3,
    name: 'Roya Islamova',
    age: 18,
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 4,
    name: 'Ayman Shaikh',
    age: 24,
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 5,
    name: 'Iftekhar Ahmed',
    age: 23,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 6,
    name: 'Cristiano Ronaldo',
    age: 37,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 7,
    name: 'Karim Benzema',
    age: 38,
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 8,
    name: 'John',
    age: 25,
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 9,
    name: 'Milana',
    age: 21,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 10,
    name: 'Gigi Hadid',
    age: 27,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 11,
    name: 'Marie',
    age: 25,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 12,
    name: 'Bella',
    age: 24,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 13,
    name: 'Rahul Gandhi',
    age: 43,
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 14,
    name: 'Arman Khan',
    age: 23,
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 15,
    name: 'Miraab',
    age: 33,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 16,
    name: 'Iman Khan',
    age: 24,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 17,
    name: 'Irshad Khan',
    age: 36,
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 18,
    name: 'Memmedeva',
    age: 20,
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 19,
    name: 'Shenja Khan',
    age: 22,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 20,
    name: 'Mahnaz Safi',
    age: 29,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 21,
    name: 'Tariq Khan',
    age: 51,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 22,
    name: 'Saif Khan',
    age: 39,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 23,
    name: 'Kaif Khan',
    age: 27,
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 24,
    name: 'Asim Rain',
    age: 23,
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 25,
    name: 'Salman Shaikh',
    age: 29,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 26,
    name: 'Sana Khan',
    age: 23,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 27,
    name: 'Shifa Malik',
    age: 21,
    address: '5060 Fairways Cir #APT 207, Vero Beach, FL, 32967',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 28,
    name: 'Sifa Khan',
    age: 19,
    address: '3501 New Haven Ave #152, Columbia, MO, 65201',
    phone: '(634) 09 3833',
    email: 'mariehoward@example.com',
  },
  {
    id: 29,
    name: 'Ruqaiyya',
    age: 23,
    address: '1545 Dorsey Ln NE, Leland, NC, 28451',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
  {
    id: 30,
    name: 'Tia Sharma',
    age: 41,
    address: '555 Front St #APT 2H, Hempstead, NY, 11550',
    phone: '(207) 808 8863',
    email: 'jenniferrobinson@example.com',
  },
];