export const doctorData = [
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 2,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
  {
    id: 1,
    name: "Cristina Groves",
    specialization: "Gynecologist",
    location: "United States, San Francisco",
    imgSrc: "assets/img/doctor-thumb-03.jpg",
  },
];

export const rowData = [
  {
    id: 1,
    code: 10001,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },
  {
    id: 2,
    code: 10002,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },
  {
    id: 3,
    code: 10003,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },
  {
    id: 4,
    code: 10004,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },
  {
    id: 5,
    code: 10005,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },
  {
    id: 6,
    code: 10006,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },
  {
    id: 7,
    code: 10007,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },
  {
    id: 8,
    code: 10008,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },
  {
    id: 9,
    code: 10009,
    imgSrc: "assets/img/user.jpg",
    name: "Jennifer Robinson",
    age: 35,
    address: "1545 Dorsey Ln NE, Leland, NC, 28451",
    phoneNumber: "(207) 808 8863",
    email: "jenniferrobinson@example.com",
  },

];

export default rowData;
